# Generated by Django 2.1.2 on 2018-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotquestion',
            name='answer_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatbotquestion',
            name='question_text',
            field=models.CharField(max_length=50),
        ),
    ]
